name: frontend
description: "A new Flutter project."
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK version required by this project
environment:
  sdk: ^3.13.2

# Packages required to run the Flutter application
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Used to select and upload item images
  image_picker: ^1.1.2

  # Used to communicate with our Flask backend through HTTP APIs
  http: ^1.5.0

  # Provides iOS-style icons
  cupertino_icons: ^1.0.8

# Packages used during development and testing
dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Recommended Dart/Flutter code quality checks
  flutter_lints: ^6.0.0

# Flutter-specific configuration
flutter:

  # Enables Material Design icons
  uses-material-design: true